services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    restart: always
    ports:
      - '8080:8080'
    networks:
      - goprom-net
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    ports:
     - '3000:3000'
    networks:
      - goprom-net
    depends_on:
      - prometheus
  prometheus:
    image: prom/prometheus:v2.52.0
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - '9090:9090'
    networks:
      - goprom-net
    restart: always
    depends_on:
      - api

volumes:
  prometheus_data:

networks:
  goprom-net:
